### ISSUE TITLE
"undefined method `[]' for nil:NilClass" in v1.5.0

### ISSUE THREAD

**Issue by baburdick** [hipchat/hipchat-rb#129]
This was working in v1.4.0, but now breaks with the following error. Somehow `@api.send_config` is `nil`:
```ruby
      response = self.class.post(@api.send_config[:url],
```
The backtrace:
```
undefined method `[]' for nil:NilClass
~/.rvm/gems/ruby-2.1.2@my_gemset/gems/hipchat-1.5.0/lib/hipchat/room.rb:122:in `send'
~/.rvm/gems/ruby-2.1.2@my_gemset/gems/hipchat-1.5.0/lib/hipchat/capistrano/tasks/hipchat.rake:46:in `block in send_message'
~/.rvm/gems/ruby-2.1.2@my_gemset/gems/hipchat-1.5.0/lib/hipchat/capistrano/tasks/hipchat.rake:44:in `each'
~/.rvm/gems/ruby-2.1.2@my_gemset/gems/hipchat-1.5.0/lib/hipchat/capistrano/tasks/hipchat.rake:44:in `send_message'
~/.rvm/gems/ruby-2.1.2@my_gemset/gems/hipchat-1.5.0/lib/hipchat/capistrano/tasks/hipchat.rake:11:in `block (2 levels) in <top (required)>'
~/.rvm/gems/ruby-2.1.2@my_gemset/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
~/.rvm/gems/ruby-2.1.2@my_gemset/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
~/.rvm/gems/ruby-2.1.2@my_gemset/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
~/.rvm/gems/ruby-2.1.2@my_gemset/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
~/.rvm/gems/ruby-2.1.2@my_gemset/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
~/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
~/.rvm/gems/ruby-2.1.2@my_gemset/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
~/.rvm/gems/ruby-2.1.2@my_gemset/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
~/.rvm/gems/ruby-2.1.2@my_gemset/gems/capistrano-3.4.0/lib/capistrano/dsl/task_enhancements.rb:14:in `block in after'
~/.rvm/gems/ruby-2.1.2@my_gemset/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
~/.rvm/gems/ruby-2.1.2@my_gemset/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
~/.rvm/gems/ruby-2.1.2@my_gemset/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
~/.rvm/gems/ruby-2.1.2@my_gemset/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
~/.rvm/gems/ruby-2.1.2@my_gemset/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
~/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
~/.rvm/gems/ruby-2.1.2@my_gemset/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
~/.rvm/gems/ruby-2.1.2@my_gemset/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
~/.rvm/gems/ruby-2.1.2@my_gemset/gems/capistrano-3.4.0/lib/capistrano/dsl.rb:16:in `invoke'
~/.rvm/gems/ruby-2.1.2@my_gemset/gems/capistrano-3.4.0/lib/capistrano/tasks/framework.rake:65:in `block (2 levels) in <top (required)>'
~/.rvm/gems/ruby-2.1.2@my_gemset/gems/capistrano-3.4.0/lib/capistrano/tasks/framework.rake:64:in `each'
~/.rvm/gems/ruby-2.1.2@my_gemset/gems/capistrano-3.4.0/lib/capistrano/tasks/framework.rake:64:in `block in <top (required)>'
~/.rvm/gems/ruby-2.1.2@my_gemset/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
~/.rvm/gems/ruby-2.1.2@my_gemset/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
~/.rvm/gems/ruby-2.1.2@my_gemset/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
~/.rvm/gems/ruby-2.1.2@my_gemset/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
~/.rvm/gems/ruby-2.1.2@my_gemset/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
~/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
~/.rvm/gems/ruby-2.1.2@my_gemset/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
~/.rvm/gems/ruby-2.1.2@my_gemset/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
~/.rvm/gems/ruby-2.1.2@my_gemset/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
~/.rvm/gems/ruby-2.1.2@my_gemset/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
~/.rvm/gems/ruby-2.1.2@my_gemset/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
~/.rvm/gems/ruby-2.1.2@my_gemset/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
~/.rvm/gems/ruby-2.1.2@my_gemset/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
~/.rvm/gems/ruby-2.1.2@my_gemset/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
~/.rvm/gems/ruby-2.1.2@my_gemset/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
~/.rvm/gems/ruby-2.1.2@my_gemset/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
~/.rvm/gems/ruby-2.1.2@my_gemset/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
~/.rvm/gems/ruby-2.1.2@my_gemset/gems/capistrano-3.4.0/lib/capistrano/application.rb:15:in `run'
~/.rvm/gems/ruby-2.1.2@my_gemset/gems/capistrano-3.4.0/bin/cap:3:in `<top (required)>'
~/.rvm/gems/ruby-2.1.2@my_gemset/bin/cap:23:in `load'
~/.rvm/gems/ruby-2.1.2@my_gemset/bin/cap:23:in `<main>'
~/.rvm/gems/ruby-2.1.2@my_gemset/bin/ruby_executable_hooks:15:in `eval'
~/.rvm/gems/ruby-2.1.2@my_gemset/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by rohitn** [comment]
+1 Seeing the same issue.

**Comment by jaredm4** [comment]
+1

**Comment by mhink** [comment]
Looks like the client initialization code was looking for options in all the wrong places ;)

https://github.com/hipchat/hipchat-rb/pull/130

**Comment by natsumisaito** [comment]
+1

**Comment by stamm** [comment]
+1

**Comment by mattkasa** [comment]
+1

**Comment by eriephillips** [comment]
+1

**Comment by rberrelleza** [comment]
Closing since the fix has been merged, please re-open if that's not the case.
